"""Adição da coluna total_price para a lógica do calculo de noites para dar o preco total

Revision ID: 7cb96777c280
Revises: be80201cb29f
Create Date: 2025-09-14 18:13:38.991084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb96777c280'
down_revision: Union[str, Sequence[str], None] = 'be80201cb29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('total_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'total_price')
    # ### end Alembic commands ###
