"""Atualizando a tabela properties

Revision ID: 80a7a048f2f6
Revises: 7662ab50cedf
Create Date: 2025-09-13 11:03:14.205249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a7a048f2f6'
down_revision: Union[str, Sequence[str], None] = '7662ab50cedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('title', sa.String(), nullable=False))
    op.drop_index(op.f('ix_properties_name'), table_name='properties')
    op.create_index(op.f('ix_properties_title'), 'properties', ['title'], unique=False)
    op.drop_column('properties', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_properties_title'), table_name='properties')
    op.create_index(op.f('ix_properties_name'), 'properties', ['name'], unique=False)
    op.drop_column('properties', 'title')
    # ### end Alembic commands ###
