"""adicionando mais colunas na propriedade

Revision ID: 8d9a80e2ee69
Revises: 8727e2c2b50c
Create Date: 2025-09-13 10:59:32.014984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9a80e2ee69'
down_revision: Union[str, Sequence[str], None] = '8727e2c2b50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('address_neighborhood', sa.String(), nullable=False))
    op.add_column('properties', sa.Column('rooms', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'rooms')
    op.drop_column('properties', 'address_neighborhood')
    # ### end Alembic commands ###
